### ISSUE TITLE
jpg图片调用compress方法，质量不对啊

### ISSUE THREAD

**Issue by zjscy666** [WangYuLue/image-conversion#1]
function view() {
            const file = document.getElementById('demo').files[0];
            console.log(file);
            imageConversion.compress(file, 0.9).then(res => {
                console.log(res);
            })
        }
图片原来size 5357333
调用后size 1189802 type: 'image/jpeg'

**Comment by WangYuLue** [comment]
你是指的什么质量不对？

**Comment by zjscy666** [comment]
我找到原因了，在转变成canvas的时候其实质量已经变了
