### ISSUE TITLE
mineType: "image/png" Issue

### ISSUE THREAD

**Issue by weilinzung** [WangYuLue/image-conversion#16]
When using `type: "image/png"`, PNG image size is getting bigger or not change at all. However, if I put that empty, I guess the default is set to `"image/png"` then has no issue.

The demo actually has the same issue.

![Screen Shot 2020-01-29 at 4 07 52 PM](https://user-images.githubusercontent.com/7368063/73397477-9c785d80-42b1-11ea-8b2e-8fced0131db2.png)

**Comment by WangYuLue** [comment]
Actually，"image/png" option is prepare for compress transparent images, if you compress common images, default it to for get better compression.

**Comment by weilinzung** [comment]
@WangYuLue 能具体一点吗？谢谢！

**Comment by WangYuLue** [comment]
js自带的API对png类型的图片压缩效果不是很好。如果想要更好的压缩效果，`type` 不要填

**Comment by weilinzung** [comment]
@WangYuLue 明白了。还有一点，png和jpg压缩的图片质量能再提高一些吗？

NODEJS 的 https://www.npmjs.com/package/imagemin-pngquant 处理得很不错, 就算图片被压缩得很小。 可惜只局限于local，要是`image-conversion` 能做到一些更好的质量提升就完美了。

**Comment by weilinzung** [comment]
> js自带的API对png类型的图片压缩效果不是很好。如果想要更好的压缩效果，`type` 不要填

再测试了一下，不选的话，图片是png的话会压缩为jpg格式。要是后缀保持是`xxx.png`的话，PS 无法打开的, 因为图片已经变为jpg了。就是说等于没办法真正压缩png图片了？

**Comment by WangYuLue** [comment]
@weilinzung 目前来说是这样，对png压缩的效果不是很好。你提到的 `imagemin-pngquant` 我会研究一下，看看能不能改良。

**Comment by weilinzung** [comment]
https://github.com/psych0der/pngquantjs
https://github.com/brunobar79/J-I-C
https://github.com/ShyykoSerhiy/canvas-png-compression

谢谢，还有这几个，您看一下能参考一下不。

**Comment by WangYuLue** [comment]
> https://github.com/psych0der/pngquantjs
> https://github.com/brunobar79/J-I-C
> https://github.com/ShyykoSerhiy/canvas-png-compression
> 
> 谢谢，还有这几个，您看一下能参考一下不。

好的，多谢
