### ISSUE TITLE
ie10浏览器报错

### ISSUE THREAD

**Issue by liu-kaixin** [WangYuLue/image-conversion#17]
<img width="1653" alt="WechatIMG2" src="https://user-images.githubusercontent.com/20205436/77132912-1cde6200-6a9c-11ea-8051-fca337a9c2de.png">

**Comment by liu-kaixin** [comment]
@WangYuLue

**Comment by qiutian00** [comment]
@WangYuLue , 有适用流浪器版本么？我在android webview使用，好像有点问题： 保存不了上传图片，然而在浏览器调试是正常的

**Comment by WangYuLue** [comment]
这个库使用了一些ES6的新方法，例如：Promise，fetch 旧版本浏览器可能不支持，我这两天看一下能不能用 babel 做一下兼容处理

**Comment by WangYuLue** [comment]
兼容IE的话会引入大量的polyfill代码，得不偿失，因此放弃支持老的浏览器
