### ISSUE TITLE
透明背景的图片压缩后背景颜色变为了黑色是什么原因呢，可以设置背景颜色为白色吗

### ISSUE THREAD

**Issue by misstakau** [WangYuLue/image-conversion#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WangYuLue** [comment]
是的，由于现阶段浏览器端压缩图片能力的限制，现在压缩png透明图片会有一些问题。

这个问题在 readme 里有提到：

Tips:
If you compress png transparent images, please select 'image/png' type.

可以尝试 手动设置  'image/png'  类型，这样压缩后还是透明图片，但是压缩效果会比较差。

**Comment by misstakau** [comment]
谢谢回复！
