### ISSUE TITLE
 在vue production 环境变量打包的时候会报这个错误 cannot set property imageConvertion of undefined

### ISSUE THREAD

**Issue by bingbingq** [WangYuLue/image-conversion#23]
import * as imageConversion from 'image-conversion'

imageConversion.compressAccurately(file.raw, 90).then(res => {
            imageConversion.compress(file.raw, {
              quality: 0.6,
              type: "image/jpeg",
              width: 20,
              scale: 0.5,
            })
          })

**Comment by WangYuLue** [comment]
能否提供更多的信息，我刚刚用 vue-cli 建了一个项目，打包测试，并没有发现这个问题
