### ISSUE TITLE
npm 打包出错呢

### ISSUE THREAD

**Issue by ifu25** [WangYuLue/image-conversion#6]
vue 项目 `npm run build` 发布应用时出错，如图：
![20190515165024243](https://user-images.githubusercontent.com/5575008/57762285-cdb7fa00-7731-11e9-98d1-acab3f02d1ce.png)

**Comment by WangYuLue** [comment]
应该是你的babel配置没有支持 async 语法，参考这个 [issue](https://github.com/WangYuLue/image-conversion/issues/4)
