### ISSUE TITLE
png格式添加type参数后压缩不到指定的size大小

### ISSUE THREAD

**Issue by FanWJ1108** [WangYuLue/image-conversion#7]
imageConversion.compressAccurately(file, {
            size: 100,
            type: `image/png`
})
300kb的大概压缩到270左右，但是不指定type是可以的。

**Comment by WangYuLue** [comment]
readme里有说明：If you compress png transparent images, please select 'image/png' type.

如果不是压缩带有透明背景的图片，建议不要指定type,这样会有更好的压缩效果；

**Comment by FanWJ1108** [comment]
嗯嗯，但是在压缩透明背景的png图片时，不加type会出现黑色背景，加type不能压缩到指定的size内，这个有办法解么～

**Comment by WangYuLue** [comment]
目前还不行
