### ISSUE TITLE
compressAccurately在移动端压缩大小不正确

### ISSUE THREAD

**Issue by zhangminggeek** [WangYuLue/image-conversion#8]
imageConversion.compressAccurately方法，设置压缩大小为300kb，在pc端压缩后大小正常，但在移动端会出现压缩后图片大小大于设置的值的情况，如3M的图片压缩后大小为400kb+

**Comment by WangYuLue** [comment]
是什么型号的设备？

**Comment by zhangminggeek** [comment]
所有型号都存在这个问题

**Comment by WangYuLue** [comment]
> 所有型号都存在这个问题

我刚刚用 iPhone7P 试了一下，2M的图片压缩成200KB，可以正常压缩

**Comment by WangYuLue** [comment]
可能是图片或者个别设备的问题

**Comment by zhangminggeek** [comment]
不是个别设备的原因，你用比较高清的摄像头拍照，华为、小米什么的，拍出的原图有10M+，这时候限定大小300kb就无法生效，可能会被压缩成400kb+或者更大的图片

**Comment by WangYuLue** [comment]
> 不是个别设备的原因，你用比较高清的摄像头拍照，华为、小米什么的，拍出的原图有10M+，这时候限定大小300kb就无法生效，可能会被压缩成400kb+或者更大的图片

会有这个问题，比较极端的情况下JS压缩图片可能不会有预期的效果，这时候可以尝试调整图片大小，来获得理想的效果。

**Comment by molvqingtai** [comment]
同样的问题，淘宝webview
